### ISSUE TITLE
Come intensità colore si parte da un criterio riconosciuto? Se si dove lo trovo?

### ISSUE THREAD

**Issue by giuragu** [opendatasicilia/covidComuniSicilia#9]
L'oggetto dovrebbe chiarire il quesito.
Mi stavo in sostanza chiedendo se la scelta della scala dei colori è dettata da un criterio riconosciuto per indicare soglie di allerta o meno. In caso affermativo dove possibile trovare questo criterio...lo indicherei. In caso negativo capirei se c'è "l'indice" relativo e proverei ad indicarlo comunque

**Comment by aborruso** [comment]
No giu, è soltanto un'interpolazione lineare tra minimo e massimo.

Non mi risulta ci sia una scala colori per indicare soglie in questo contesto. Al momento la mappa ti dice dove ci sono più positivi (ogni 1000 residenti): un colore intenso non indica alcuna allerta, ma soltanto che ci sono più casi.

Se la risposta per te è buona, please chiudi issue

![image](https://user-images.githubusercontent.com/30607/100589938-04456d80-32f4-11eb-8e96-f538d589de5e.png)

**Comment by giuragu** [comment]
Ok @aborruso grazie mille. Si per il momento si
